DNA_START_CODON = 'ATG'
DNA_STOP_CODONS = ['TAA','TGA','TAG']

STD_DNA_CODON_TAB = {
	'TTT' : 'F',
	'TCT' : 'S',
	'TAT' : 'Y',
	'TGT' : 'C',
	'TTC' : 'F',
	'TCC' : 'S',
	'TAC' : 'Y',
	'TGC' : 'C',
	'TTA' : 'L',
	'TCA' : 'S',
	'TAA' : '*',
	'TGA' : '*',
	'TTG' : 'L',
	'TCG' : 'S',
	'TAG' : '*',
	'TGG' : 'W',
	'CTT' : 'L',
	'CCT' : 'P',
	'CAT' : 'H',
	'CGT' : 'R',
	'CTC' : 'L',
	'CCC' : 'P',
	'CAC' : 'H',
	'CGC' : 'R',
	'CTA' : 'L',
	'CCA' : 'P',
	'CAA' : 'Q',
	'CGA' : 'R',
	'CTG' : 'L',
	'CCG' : 'P',
	'CAG' : 'Q',
	'CGG' : 'R',
	'ATT' : 'I',
	'ACT' : 'T',
	'AAT' : 'N',
	'AGT' : 'S',
	'ATC' : 'I',
	'ACC' : 'T',
	'AAC' : 'N',
	'AGC' : 'S',
	'ATA' : 'I',
	'ACA' : 'T',
	'AAA' : 'K',
	'AGA' : 'R',
	'ATG' : 'M',
	'ACG' : 'T',
	'AAG' : 'K',
	'AGG' : 'R',
	'GTT' : 'V',
	'GCT' : 'A',
	'GAT' : 'D',
	'GGT' : 'G',
	'GTC' : 'V',
	'GCC' : 'A',
	'GAC' : 'D',
	'GGC' : 'G',
	'GTA' : 'V',
	'GCA' : 'A',
	'GAA' : 'E',
	'GGA' : 'G',
	'GTG' : 'V',
	'GCG' : 'A',
	'GAG' : 'E',
	'GGG' : 'G'
}

STD_RNA_CODON_TAB = {
	'UUU' : 'F',
	'UCU' : 'S',
	'UAU' : 'Y',
	'UGU' : 'C',
	'UUC' : 'F',
	'UCC' : 'S',
	'UAC' : 'Y',
	'UGC' : 'C',
	'UUA' : 'L',
	'UCA' : 'S',
	'UAA' : '*',
	'UGA' : '*',
	'UUG' : 'L',
	'UCG' : 'S',
	'UAG' : '*',
	'UGG' : 'W',
	'CUU' : 'L',
	'CCU' : 'P',
	'CAU' : 'H',
	'CGU' : 'R',
	'CUC' : 'L',
	'CCC' : 'P',
	'CAC' : 'H',
	'CGC' : 'R',
	'CUA' : 'L',
	'CCA' : 'P',
	'CAA' : 'Q',
	'CGA' : 'R',
	'CUG' : 'L',
	'CCG' : 'P',
	'CAG' : 'Q',
	'CGG' : 'R',
	'AUU' : 'I',
	'ACU' : 'T',
	'AAU' : 'N',
	'AGU' : 'S',
	'AUC' : 'I',
	'ACC' : 'T',
	'AAC' : 'N',
	'AGC' : 'S',
	'AUA' : 'I',
	'ACA' : 'T',
	'AAA' : 'K',
	'AGA' : 'R',
	'AUG' : 'M',
	'ACG' : 'T',
	'AAG' : 'K',
	'AGG' : 'R',
	'GUU' : 'V',
	'GCU' : 'A',
	'GAU' : 'D',
	'GGU' : 'G',
	'GUC' : 'V',
	'GCC' : 'A',
	'GAC' : 'D',
	'GGC' : 'G',
	'GUA' : 'V',
	'GCA' : 'A',
	'GAA' : 'E',
	'GGA' : 'G',
	'GUG' : 'V',
	'GCG' : 'A',
	'GAG' : 'E',
	'GGG' : 'G'
}

TABLE_DIFFS = [
	set([]),
	set([]),
	set([('AGA', '*'), 	#transl_table=2
 	     ('AGG', '*'),
 	     ('ATA', 'M'),
 	     ('TGA', 'W')]),
	set([('ATA', 'M'),	#transl_table=3
 	     ('CTT', 'T'),
 	     ('CTC', 'T'),
             ('CTA', 'T'),
             ('CTG', 'T'),
             ('TGA', 'W'),
             ('CGA', None),
             ('CGC', None)]),
	set([('TGA', 'W')]),	#transl_table=4
	set([('AGA', 'S'),     #transl_table=5
 	     ('AGG', 'S'),
             ('ATA', 'M'),
             ('TGA', 'W')]),
	set([('TAA', 'Q'),	#transl_table=6
 	     ('TAG', 'Q')]),
	set([]),		#transl_table=7
	set([]),		#transl_table=8
	set([('AAA', 'N'),	#transl_table=9
             ('AGA', 'S'),
             ('AGG', 'S'),
             ('TGA', 'W')]),
	set([('TGA', 'C')]),	#transl_table=10
	set([]),		#transl_table=11
	set([('CTG', '*')]),	#transl_table=12
	set([('AGA', 'G'),     #transl_table=13
 	     ('AGG', 'G'),
             ('ATA', 'M'),
             ('TGA', 'W')]),
	set([('AAA', 'N'),     #transl_table=14
 	     ('AGA', 'S'),
             ('AGG', 'S'),
	     ('TAA', 'Y'),
             ('TGA', 'W')]),
	set([('TAG', 'Q')])   #transl_table=15
]
